name: Tests

on:
  pull_request:

jobs:
  test-upload-coverage:
    name: Upload coverage reports
    runs-on: ubuntu-22.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: coverage_*_88b7a248e362b665a6e70e800cbbcf97961685c0
      # Codecov will search all directories for coverage reports and upload them
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

