name: Tests

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip tox
      - name: Run lint
        run: tox -e qa
  tests:
    name: Run tests
    uses: ./.github/workflows/shared/tests.yml
